# Configuration for synthetic regression experiments

# Data generation parameters
data:
  n_samples: 1000  # Number of data points
  dimension: 20    # Feature dimension
  noise_std_values: [0.1, 1.0, 5.0]  # Noise standard deviations to test
  seeds: [0, 42, 1337]  # Random seeds for reproducibility

# Training parameters
training:
  epochs: 20  # Number of training epochs
  batch_sizes: [1, 16, 64, 256, "full"]  # Batch sizes to test (full = use all data)
  
# Optimizer parameters
optimizer:
  # Learning rates for grid search (constant step size)
  learning_rates: [0.001, 0.01, 0.1, 1.0]
  
  # Polyak step size parameters
  polyak:
    eps: 1.0e-8  # Small constant for numerical stability
    f_star: 0.0  # Known minimum value of the loss function
    
  # PolyakAdam parameters
  polyak_adam:
    alpha: 0.003  # Base learning rate
    polyak_factor: 0.3  # Factor to control the influence of Polyak step size
    amsgrad: false  # Whether to use the AMSGrad variant

# Logging parameters
logging:
  log_dir: "results/logs/synthetic_regression"
  save_interval: 1  # Save logs every N epochs
